const rssFeeds = [
  { name: "الرئيسي (جميع الأخبار)", slug: "", url: "https://aljnoubvoice.com/api/rss" },
  { name: "أخبار عدن", slug: "aden", url: "https://aljnoubvoice.com/api/rss/aden" },
  { name: "أخبار محلية", slug: "local", url: "https://aljnoubvoice.com/api/rss/local" },
  { name: "أخبار وتقارير", slug: "reports", url: "https://aljnoubvoice.com/api/rss/reports" },
  { name: "اليمن في الصحافة", slug: "press", url: "https://aljnoubvoice.com/api/rss/press" },
  { name: "شؤون دولية", slug: "intl", url: "https://aljnoubvoice.com/api/rss/intl" },
  { name: "آراء واتجاهات", slug: "opinions", url: "https://aljnoubvoice.com/api/rss/opinions" },
  { name: "علوم وتكنولوجيا", slug: "tech", url: "https://aljnoubvoice.com/api/rss/tech" },
  { name: "رياضة", slug: "sports", url: "https://aljnoubvoice.com/api/rss/sports" },
  { name: "فيديو", slug: "video", url: "https://aljnoubvoice.com/api/rss/video" },
  { name: "اقتصاد", slug: "economy", url: "https://aljnoubvoice.com/api/rss/economy" },
  { name: "ثقافة وفن", slug: "culture", url: "https://aljnoubvoice.com/api/rss/culture" },
  { name: "صحة", slug: "health", url: "https://aljnoubvoice.com/api/rss/health" },
  { name: "منوعات", slug: "misc", url: "https://aljnoubvoice.com/api/rss/misc" },
];
